version: 0.2

phases:
  install:
    commands:
      - echo 'Install phase...'
  pre_build:
    commands:
      - echo 'Pre-build phase...'
      - node --version
      - cd src
      - npm install express
      - npm install mocha
      - npm install supertest
      - alias mocha="node_modules/.bin/mocha"
  build:
    commands:
      - echo 'Build phase...'
      - echo "Build started on `date`"
      - mocha -R spec spec.js
