version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Pre-build phase...'
      - node --version
      - export PATH=$PATH:"/node_modules/.bin/mocha"
  build:
    commands:
      - echo 'Build phase...'
      - echo "Build started on `date`"
      - cd src
      - ls -l
      - pwd
      - mocha -R spec spec.js
