version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Pre-build phase...'
      - node --version
      - export PATH=/node_modules/.bin:$PATH
  build:
    commands:
      - echo 'Build phase...'
      - echo "Build started on `date`"
      - cd src
      - mocha -R spec spec.js
